pdel_PATH= ${PDELTOP}/pdel

pdel_BASEINCS+= \
		pd_base.h \
		pd_io.h \
		pd_mem.h \
		pd_inet.h \
		pd_poll.h \
		pd_port.h \
		pd_regex.h \
		pd_string.h \
        pd_sys.h \
        pd_syslog.h \
		pd_thread.h \
		pd_time.h
